### ISSUE TITLE
Some African Countries (Burkina Faso, Sierra Leone) Build failed

### ISSUE THREAD

**Issue by AlbertRockG** [nextstrain/ncov-africa-cdc#5]
### Current Behavior
I would like to run a build for some specific African countries. So I firstly try to run your builds before modifying the YAML file. Because interested in [CAMES](https://www.lecames.org/) (African and Malagasy Council for Higher Education), I checked out the build of countries belonging to this organisation, but some are actually missing. I have also check out the build of western africa and noticed that auspice was not able to select those countries (Burkina Faso and Sierra Leone for instance). This behaviour was noticed on the local run and also on nextstrain.org.
![Screenshot from 2022-12-06 22-30-05](https://user-images.githubusercontent.com/68031254/206043152-da1b8510-787d-4e40-881c-6751c70192b3.png)
![Screenshot from 2022-12-06 22-30-42](https://user-images.githubusercontent.com/68031254/206043155-6e2f0a36-1237-460b-9995-ee403d229148.png)
![Screenshot from 2022-12-07 00-30-32](https://user-images.githubusercontent.com/68031254/206047975-a14000be-53aa-4a61-bde6-ca0a8d6d854a.png)
![Screenshot from 2022-12-07 00-31-10](https://user-images.githubusercontent.com/68031254/206047985-48d5ca66-9285-48ad-beb7-00e6849894fd.png)
![Screenshot from 2022-12-07 00-33-27](https://user-images.githubusercontent.com/68031254/206048429-50f707f7-4845-459e-9e1d-bb70f4611275.png)
![Screenshot from 2022-12-07 00-35-03](https://user-images.githubusercontent.com/68031254/206048433-2f0fd793-575d-426a-8fe1-d60c62d4eaa5.png)

### How to reproduce
[Steps to reproduce the current behavior](https://github.com/nextstrain/ncov-africa-cdc/blob/main/README.md).

### Your environment: if browsing Nextstrain online
 - Operating system: Ubuntu 20.04 LTS
 - Browser: firefox

### Your environment: if running Nextstrain locally
 - Operating system: Ubuntu 20.04 LTS
 - Browser: firefox
 - Version: auspice 2.41

**Comment by j23414** [comment]
Hi @AlbertRockG! We just merged https://github.com/nextstrain/ncov/pull/988 which should fix this issue. Thanks for reaching out!

Should be able to pull a new ncov and run a test for Burkina Faso using:

```
nextstrain build \
  --cpus 4 \
  --memory 8Gib \
  . \
  --configfile ../ncov-africa-cdc/builds_africa.yaml \
  --config active_builds=burkina-faso
```

But please let us know if the issue persists.

**Comment by AlbertRockG** [comment]
Sorry, I just try it and the issue persists.

![Image](https://user-images.githubusercontent.com/68031254/206549529-942e23d9-c8ac-4e7a-95df-1d838af933b5.png)

**Comment by j23414** [comment]
Hi @AlbertRockG any interest in jumping on a zoom call? That way I can take a look?

My initial impression is you may need to pull the new ncov or delete a cached run (remove .snakemake and several intermediate files from data). It might be easiest to run from the top of  https://github.com/nextstrain/ncov-africa-cdc in a new folder.

**Comment by AlbertRockG** [comment]
Sure! You're right, it's easier. Can we do it now, please?

**Comment by j23414** [comment]
Sure! I'm at https://us06web.zoom.us/j/87629428441?pwd=T0ducDB0ZVVaTE1KemZVNmNKWVhOdz09

**Comment by AlbertRockG** [comment]
@j23414 Thanks a lot, it worked! 
![Screenshot from 2022-12-09 11-28-05](https://user-images.githubusercontent.com/68031254/206683273-2d8099a4-bf1f-4f90-8c25-d45165ee7877.png)
